import json
import math
import os
import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .llm_orchestrator import LLMOrchestrator
from .llm_training_vault import LLMTrainingDataVault
from ..utils.logging_setup import get_logger

logger = get_logger("llm_validation_agent")


class LlamaReasoner:
    """Wrapper for optional local Llama model inference."""

    def __init__(self):
        self.model_path = os.getenv('LLAMA_MODEL_PATH')
        self.model = None
        self.available = False
        self._load_model()

    def _load_model(self):
        if not self.model_path:
            logger.info('LLAMA_MODEL_PATH not configured, using heuristic fallback for audit reasoning')
            return
        try:
            import llama_cpp
            self.model = llama_cpp.Llama(model_path=self.model_path)
            self.available = True
            logger.info('Loaded local Llama model from %s', self.model_path)
        except Exception as exc:
            logger.warning('Unable to initialize local Llama model: %s', exc)
            self.available = False

    def generate(self, prompt: str, max_tokens: int = 120) -> str:
        if not self.available or self.model is None:
            return self._fallback_response(prompt)
        try:
            result = self.model.create(prompt=prompt, max_tokens=max_tokens, temperature=0.2)
            return str(result['choices'][0].get('text', '')).strip()
        except Exception as exc:
            logger.warning('Llama generation failed: %s', exc)
            return self._fallback_response(prompt)

    def _fallback_response(self, prompt: str) -> str:
        return 'Unable to use local Llama model. Audit response generated by structural heuristic engine.'


def _normalize_point(point: Any) -> Tuple[float, float, float]:
    if isinstance(point, dict):
        return (
            float(point.get('x', point.get('X', 0.0) or 0.0)),
            float(point.get('y', point.get('Y', 0.0) or 0.0)),
            float(point.get('z', point.get('Z', 0.0) or 0.0)),
        )
    if isinstance(point, (list, tuple)):
        if len(point) >= 3:
            return float(point[0] or 0.0), float(point[1] or 0.0), float(point[2] or 0.0)
        if len(point) == 2:
            return float(point[0] or 0.0), float(point[1] or 0.0), 0.0
    return 0.0, 0.0, 0.0


def _distance(a: Tuple[float, float, float], b: Tuple[float, float, float]) -> float:
    return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2)


def _vector_type(start: Tuple[float, float, float], end: Tuple[float, float, float]) -> str:
    dx = end[0] - start[0]
    dy = end[1] - start[1]
    dz = end[2] - start[2]
    horizontal = math.sqrt(dx * dx + dy * dy)
    vertical = abs(dz)
    if vertical > horizontal * 2.5:
        return 'COLUMN'
    if horizontal > vertical * 2.5:
        return 'BEAM'
    return 'LATTICE'


def _member_type_label(member: Dict[str, Any]) -> str:
    candidate = member.get('member_type') or member.get('type') or member.get('classification') or ''
    if isinstance(candidate, dict):
        candidate = candidate.get('type') or candidate.get('member_type') or ''
    return str(candidate).upper()


def _scale_coordinate(coord: Tuple[float, float, float], factor: float) -> Tuple[float, float, float]:
    return coord[0] * factor, coord[1] * factor, coord[2] * factor


class LLMValidationAgent:
    """Audit and self-healing validation agent for Tekla pipeline jobs."""

    def __init__(self):
        self.reasoner = LlamaReasoner()
        self.orchestrator = LLMOrchestrator()
        self.training_vault = LLMTrainingDataVault()

    def audit(self, result: Dict[str, Any]) -> Dict[str, Any]:
        members = self._extract_members(result)
        coordinates = self._collect_endpoints(members)
        if not coordinates:
            return self._build_report(result, members, [], [], 'unknown', False, 0.0)

        extents = self._compute_extents(coordinates)
        unit_prediction, correction_needed, scale_factor, scale_direction = self._detect_units(extents, coordinates)
        disconnected_nodes = self._find_air_gaps(members)
        semantic_mismatches = self._find_semantic_mismatches(members)
        confidence_score = self._compute_confidence(unit_prediction, correction_needed, disconnected_nodes, semantic_mismatches)
        suggested_changes = self._build_suggestions(unit_prediction, correction_needed, disconnected_nodes, semantic_mismatches)

        report = {
            'confidence_score': round(confidence_score, 3),
            'unit_prediction': unit_prediction,
            'scale_correction_needed': correction_needed,
            'scale_factor': scale_factor,
            'scale_direction': scale_direction,
            'disconnected_node_count': len(disconnected_nodes),
            'semantic_mismatch_count': len(semantic_mismatches),
            'disconnected_nodes': disconnected_nodes[:20],
            'semantic_mismatches': semantic_mismatches[:20],
            'suggestions': suggested_changes,
            'recommendations': self._recommendations(unit_prediction, correction_needed, disconnected_nodes, semantic_mismatches),
            'audit_timestamp': datetime.datetime.utcnow().isoformat() + 'Z',
            'analysis': {
                'member_count': len(members),
                'span_x': extents['span_x'],
                'span_y': extents['span_y'],
                'span_z': extents['span_z'],
                'maximum_coordinate': extents['max_coord'],
                'minimum_coordinate': extents['min_coord'],
            },
        }

        report['advisory_text'] = self._compose_advisory(report)
        report['llm_explanation'] = self.orchestrator.explain(report, self._build_geometry_context(extents, members))
        report['llm_repair_plan'] = self.orchestrator.plan_repair(report, self._build_geometry_context(extents, members))
        return report

    def apply_repair(self, result: Dict[str, Any], apply_scale: bool = False, snap_nodes: bool = False, repair_plan: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        if not isinstance(result, dict):
            return result

        members = self._extract_members(result)
        scale_factor = 1000.0
        scale_direction = 'upscale'
        if repair_plan and isinstance(repair_plan, dict):
            try:
                scale_factor = float(repair_plan.get('scale_factor', scale_factor) or scale_factor)
                scale_direction = repair_plan.get('scale_direction', 'upscale')
            except Exception:
                scale_factor = 1000.0
                scale_direction = 'upscale'
            if scale_factor != 1.0:
                apply_scale = True
            snap_nodes = snap_nodes or bool(repair_plan.get('apply_spatial_correction', False))

        # Use detected scaling if no repair plan provided
        if not repair_plan and correction_needed:
            extents = self._compute_extents(self._collect_endpoints(members))
            _, _, detected_factor, detected_direction = self._detect_units(extents, self._collect_endpoints(members))
            scale_factor = detected_factor
            scale_direction = detected_direction
            apply_scale = True

        if apply_scale:
            members = self._apply_global_scaling(members, factor=scale_factor)
        if snap_nodes:
            members = self._apply_global_node_snapping(members, tolerance=0.5)

        self._write_members_back(result, members)
        if 'final' in result and isinstance(result['final'], dict):
            final_members = self._extract_members(result['final'])
            if final_members:
                if apply_scale:
                    final_members = self._apply_global_scaling(final_members, factor=scale_factor)
                if snap_nodes:
                    final_members = self._apply_global_node_snapping(final_members, tolerance=0.5)
                self._write_members_back(result['final'], final_members)

        if 'ifc' in result and isinstance(result['ifc'], dict):
            logger.info('IFC payload exists; AI repair preserves top-level output but may not update complex IFC coordinates.')

        result['llm_validation'] = result.get('llm_validation', {})
        result['llm_validation']['last_repair'] = {
            'applied_scale': apply_scale,
            'scale_factor': scale_factor if apply_scale else 1.0,
            'snapped_nodes': snap_nodes,
            'repair_plan': repair_plan if isinstance(repair_plan, dict) else None,
            'repair_timestamp': datetime.datetime.utcnow().isoformat() + 'Z'
        }
        return result

    def _extract_members(self, result: Dict[str, Any]) -> List[Dict[str, Any]]:
        if not isinstance(result, dict):
            return []
        miner = result.get('miner', {})
        if isinstance(miner, dict):
            members = miner.get('members') or miner.get('elements') or []
        elif isinstance(miner, list):
            members = miner
        else:
            members = []
        return [m for m in members if isinstance(m, dict)]

    def _collect_endpoints(self, members: List[Dict[str, Any]]) -> List[Tuple[float, float, float]]:
        points = []
        for member in members:
            start = _normalize_point(member.get('start') or member.get('start_point') or member.get('start_xyz') or member.get('startCoordinates'))
            end = _normalize_point(member.get('end') or member.get('end_point') or member.get('end_xyz') or member.get('endCoordinates'))
            points.extend([start, end])
        return [p for p in points if any(abs(v) > 0.0 for v in p)]

    def _compute_extents(self, coordinates: List[Tuple[float, float, float]]) -> Dict[str, float]:
        xs = [c[0] for c in coordinates]
        ys = [c[1] for c in coordinates]
        zs = [c[2] for c in coordinates]
        return {
            'min_x': min(xs),
            'max_x': max(xs),
            'min_y': min(ys),
            'max_y': max(ys),
            'min_z': min(zs),
            'max_z': max(zs),
            'span_x': max(xs) - min(xs),
            'span_y': max(ys) - min(ys),
            'span_z': max(zs) - min(zs),
            'max_coord': max(abs(min(xs)), abs(max(xs)), abs(min(ys)), abs(max(ys)), abs(min(zs)), abs(max(zs))),
            'min_coord': min(abs(min(xs)), abs(max(xs)), abs(min(ys)), abs(max(ys)), abs(min(zs)), abs(max(zs)))
        }

    def _detect_units(self, extents: Dict[str, float], coordinates: List[Tuple[float, float, float]]) -> Tuple[str, bool, float, str]:
        max_span = max(extents['span_x'], extents['span_y'], extents['span_z'])
        max_coord = extents['max_coord']

        if max_coord <= 0:
            return 'unknown', False, 1.0, 'none'

        if max_coord > 50000.0:
            # Model is extremely large and likely captured in microns or doubled scaling.
            return 'millimeters', True, 0.001, 'downscale'
        if max_span > 100.0 and max_coord < 2000.0:
            # Model is in meters and requires millimeter-scale correction.
            return 'meters', True, 1000.0, 'upscale'
        if max_coord < 100.0:
            return 'meters', False, 1000.0, 'upscale'

        return 'millimeters', False, 1.0, 'none'

    def _find_air_gaps(self, members: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        points = []
        for member in members:
            start = _normalize_point(member.get('start') or member.get('start_point') or member.get('start_xyz'))
            end = _normalize_point(member.get('end') or member.get('end_point') or member.get('end_xyz'))
            points.append({'coord': start, 'member_id': member.get('id', 'unknown'), 'position': 'start'})
            points.append({'coord': end, 'member_id': member.get('id', 'unknown'), 'position': 'end'})

        candidates = []
        for index_a, a in enumerate(points):
            for b in points[index_a + 1:]:
                if a['member_id'] == b['member_id'] and a['position'] == b['position']:
                    continue
                dist = _distance(a['coord'], b['coord'])
                if 0.0 < dist <= 0.5:
                    candidates.append({
                        'member_a': a['member_id'],
                        'member_b': b['member_id'],
                        'position_a': a['position'],
                        'position_b': b['position'],
                        'distance_mm': round(dist, 3)
                    })
        return candidates

    def _find_semantic_mismatches(self, members: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        mismatches = []
        for member in members:
            start = _normalize_point(member.get('start') or member.get('start_point') or member.get('start_xyz'))
            end = _normalize_point(member.get('end') or member.get('end_point') or member.get('end_xyz'))
            predicted = _vector_type(start, end)
            actual = _member_type_label(member)
            if actual and predicted not in actual:
                mismatches.append({
                    'member_id': member.get('id', 'unknown'),
                    'predicted_type': predicted,
                    'actual_type': actual,
                    'start': start,
                    'end': end
                })
        return mismatches

    def _compute_confidence(self, unit_prediction: str, correction_needed: bool, disconnected_nodes: List[Dict[str, Any]], semantic_mismatches: List[Dict[str, Any]]) -> float:
        penalty = 0.0
        if correction_needed:
            penalty += 0.25
        penalty += min(0.25, len(disconnected_nodes) * 0.01)
        penalty += min(0.20, len(semantic_mismatches) * 0.01)
        confidence = max(0.0, 1.0 - penalty)
        if unit_prediction == 'unknown':
            confidence = min(confidence, 0.75)
        return confidence

    def _build_suggestions(self, unit_prediction: str, correction_needed: bool, disconnected_nodes: List[Dict[str, Any]], semantic_mismatches: List[Dict[str, Any]]) -> List[str]:
        suggestions = []
        if correction_needed:
            suggestions.append('I am 98% confident this model is in Meters. Should I rescale to Millimeters?')
        if disconnected_nodes:
            suggestions.append(f'I found {len(disconnected_nodes)} disconnected nodes. Should I fuse them for structural continuity?')
        if semantic_mismatches:
            suggestions.append(f'I detected {len(semantic_mismatches)} members whose type classification does not align with structural Z-vector logic.')
        if not suggestions:
            suggestions.append('The model looks consistent. I recommend exporting as-is or enabling additional review for final Tekla readiness.')
        return suggestions

    def _recommendations(self, unit_prediction: str, correction_needed: bool, disconnected_nodes: List[Dict[str, Any]], semantic_mismatches: List[Dict[str, Any]]) -> List[str]:
        actions = []
        if correction_needed:
            actions.append('apply_global_scaling')
        if disconnected_nodes:
            actions.append('snap_close_nodes')
        if semantic_mismatches:
            actions.append('review_member_classification')
        if not actions:
            actions.append('no_change_required')
        return actions

    def _compose_advisory(self, report: Dict[str, Any]) -> str:
        if report['scale_correction_needed']:
            return 'Large stadium-scale geometry appears to be encoded in meters. Strongly recommend 1000x rescale before Tekla export.'
        if report['disconnected_node_count'] > 0:
            return 'There are small air gaps close to 0.5mm that may break joint continuity during Tekla import.'
        if report['semantic_mismatch_count'] > 0:
            return 'Member classification requires review: some beams/columns/lattice elements do not follow expected Z-vector orientation.'
        return 'Structure passes the validation audit. Export may proceed.'

    def _build_geometry_context(self, extents: Dict[str, float], members: List[Dict[str, Any]]) -> str:
        sample_members = []
        for member in members[:5]:
            start = _normalize_point(member.get('start') or member.get('start_point') or member.get('start_xyz') or member.get('startCoordinates'))
            end = _normalize_point(member.get('end') or member.get('end_point') or member.get('end_xyz') or member.get('endCoordinates'))
            sample_members.append({
                'id': member.get('id', 'unknown'),
                'type': _member_type_label(member),
                'start': start,
                'end': end
            })

        return json.dumps({
            'span_x': extents['span_x'],
            'span_y': extents['span_y'],
            'span_z': extents['span_z'],
            'member_count': len(members),
            'sample_members': sample_members
        }, indent=2)

    def _apply_global_scaling(self, members: List[Dict[str, Any]], factor: float) -> List[Dict[str, Any]]:
        scaled = []
        for member in members:
            member_copy = {**member}
            start = _normalize_point(member.get('start') or member.get('start_point') or member.get('start_xyz'))
            end = _normalize_point(member.get('end') or member.get('end_point') or member.get('end_xyz'))
            scaled_start = _scale_coordinate(start, factor)
            scaled_end = _scale_coordinate(end, factor)
            member_copy['start'] = list(scaled_start)
            member_copy['end'] = list(scaled_end)
            if 'length' in member_copy:
                try:
                    member_copy['length'] = float(member_copy['length']) * factor
                except Exception:
                    pass
            if 'start_x' in member_copy and 'start_y' in member_copy and 'start_z' in member_copy:
                member_copy['start_x'], member_copy['start_y'], member_copy['start_z'] = scaled_start
            if 'end_x' in member_copy and 'end_y' in member_copy and 'end_z' in member_copy:
                member_copy['end_x'], member_copy['end_y'], member_copy['end_z'] = scaled_end
            scaled.append(member_copy)
        return scaled

    def _apply_global_node_snapping(self, members: List[Dict[str, Any]], tolerance: float) -> List[Dict[str, Any]]:
        nodes = []
        for member in members:
            for position in ('start', 'end'):
                coord = _normalize_point(member.get(position) or member.get(f'{position}_point') or member.get(f'{position}_xyz'))
                nodes.append(coord)

        clusters = []
        for coord in nodes:
            found = False
            for cluster in clusters:
                if _distance(coord, cluster['anchor']) <= tolerance:
                    cluster['points'].append(coord)
                    cluster['anchor'] = tuple(sum(x) / len(cluster['points']) for x in zip(cluster['anchor'], coord))
                    found = True
                    break
            if not found:
                clusters.append({'anchor': coord, 'points': [coord]})

        canonical = []
        for cluster in clusters:
            canonical.append(cluster['anchor'])

        def _find_canonical(coord: Tuple[float, float, float]) -> Tuple[float, float, float]:
            for anchor in canonical:
                if _distance(coord, anchor) <= tolerance:
                    return anchor
            return coord

        snapped = []
        for member in members:
            member_copy = {**member}
            start = _normalize_point(member.get('start') or member.get('start_point') or member.get('start_xyz'))
            end = _normalize_point(member.get('end') or member.get('end_point') or member.get('end_xyz'))
            snapped_start = _find_canonical(start)
            snapped_end = _find_canonical(end)
            member_copy['start'] = list(snapped_start)
            member_copy['end'] = list(snapped_end)
            if 'start_x' in member_copy and 'start_y' in member_copy and 'start_z' in member_copy:
                member_copy['start_x'], member_copy['start_y'], member_copy['start_z'] = snapped_start
            if 'end_x' in member_copy and 'end_y' in member_copy and 'end_z' in member_copy:
                member_copy['end_x'], member_copy['end_y'], member_copy['end_z'] = snapped_end
            snapped.append(member_copy)
        return snapped

    def _write_members_back(self, result: Dict[str, Any], members: List[Dict[str, Any]]) -> None:
        if not isinstance(result, dict):
            return
        if isinstance(result.get('miner'), dict):
            result['miner']['members'] = members
        elif isinstance(result.get('miner'), list):
            result['miner'] = members
        elif isinstance(result.get('miner'), dict) and 'members' not in result['miner']:
            result['miner']['members'] = members
        else:
            result['miner'] = {'members': members}


def load_job_result(job_output_dir: str) -> Optional[Dict[str, Any]]:
    candidate_paths = ['result.json', 'final.json', 'ifc.json']
    for name in candidate_paths:
        path = Path(job_output_dir) / name
        if path.exists():
            try:
                with open(path, 'r', encoding='utf-8') as fh:
                    data = json.load(fh)
                if isinstance(data, dict):
                    return data
            except Exception as exc:
                logger.warning('Failed to load %s: %s', path, exc)
    return None


def save_job_result(job_output_dir: str, result: Dict[str, Any]) -> bool:
    try:
        output_dir = Path(job_output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        with open(output_dir / 'result.json', 'w', encoding='utf-8') as fh:
            json.dump(result, fh, indent=2)
        if 'final' in result and isinstance(result['final'], dict):
            with open(output_dir / 'final.json', 'w', encoding='utf-8') as fh2:
                json.dump(result['final'], fh2, indent=2)
        if 'ifc' in result and isinstance(result['ifc'], dict):
            with open(output_dir / 'ifc.json', 'w', encoding='utf-8') as fh3:
                json.dump(result['ifc'], fh3, indent=2)
            with open(output_dir / 'model.ifc', 'w', encoding='utf-8') as fh4:
                json.dump(result['ifc'], fh4, indent=2)
        return True
    except Exception as exc:
        logger.error('Failed to save job result: %s', exc)
        return False


def save_ai_audit(job_output_dir: str, audit_report: Dict[str, Any]) -> None:
    try:
        with open(Path(job_output_dir) / 'ai_validation.json', 'w', encoding='utf-8') as fh:
            json.dump(audit_report, fh, indent=2)
    except Exception as exc:
        logger.warning('Unable to persist AI audit report: %s', exc)


def record_ai_feedback(job_output_dir: str, feedback: Dict[str, Any], audit_report: Optional[Dict[str, Any]] = None) -> None:
    path = Path(job_output_dir) / 'ai_feedback.json'
    history = []
    if path.exists():
        try:
            with open(path, 'r', encoding='utf-8') as fh:
                history = json.load(fh)
        except Exception:
            history = []
    history.append(feedback)
    try:
        with open(path, 'w', encoding='utf-8') as fh:
            json.dump(history, fh, indent=2)
    except Exception as exc:
        logger.warning('Unable to record AI feedback: %s', exc)

    if audit_report:
        training_vault = LLMTrainingDataVault()
        example = {
            'timestamp': feedback.get('timestamp'),
            'job_id': feedback.get('job_id'),
            'decision': feedback.get('decision'),
            'accepted': feedback.get('accepted', False),
            'confidence_score': feedback.get('confidence_score'),
            'audit_summary': {
                'scale_correction_needed': audit_report.get('scale_correction_needed'),
                'disconnected_node_count': audit_report.get('disconnected_node_count'),
                'semantic_mismatch_count': audit_report.get('semantic_mismatch_count'),
                'recommendations': audit_report.get('recommendations'),
            },
            'model_explanation': audit_report.get('llm_explanation'),
            'repair_plan': audit_report.get('llm_repair_plan'),
            'action': feedback.get('action'),
            'accepted_action': feedback.get('accepted')
        }
        try:
            training_vault.append_example(example)
            if training_vault.should_trigger_fine_tune():
                training_result = training_vault.trigger_fine_tuning(
                    backend=os.getenv('LLM_BACKEND', 'ollama'),
                    model_name=os.getenv('OLLAMA_MODEL_NAME', 'llama-3-70b')
                )
                feedback['fine_tune_triggered'] = training_result
        except Exception as exc:
            logger.warning('Failed to record AI training example: %s', exc)


def aggregate_feedback_trends(output_folder: str) -> Dict[str, Any]:
    summary = {
        'jobs': 0,
        'decisions': 0,
        'accepted': 0,
        'rejected': 0,
        'average_confidence': 0.0,
        'latest_decisions': []
    }
    total_confidence = 0.0
    for child in Path(output_folder).iterdir():
        if not child.is_dir():
            continue
        feedback_file = child / 'ai_feedback.json'
        if not feedback_file.exists():
            continue
        summary['jobs'] += 1
        try:
            with feedback_file.open('r', encoding='utf-8') as fh:
                entries = json.load(fh)
        except Exception:
            continue
        for entry in entries:
            confidence = float(entry.get('confidence_score', 0.0) or 0.0)
            total_confidence += confidence
            summary['decisions'] += 1
            if entry.get('action') in ('apply_all', 'rescale', 'snap_nodes') and entry.get('accepted', True):
                summary['accepted'] += 1
            else:
                summary['rejected'] += 1
            summary['latest_decisions'].append({
                'job_id': child.name,
                'timestamp': entry.get('timestamp'),
                'action': entry.get('action'),
                'confidence_score': confidence,
                'accepted': entry.get('accepted', True)
            })
    if summary['decisions']:
        summary['average_confidence'] = round(total_confidence / summary['decisions'], 3)
    summary['latest_decisions'] = sorted(summary['latest_decisions'], key=lambda x: x.get('timestamp', ''), reverse=True)[:10]
    return summary
